apiVersion: v1
name: dp-image-admission-controller
description: Data Platform Image Admission Controller Helm Chart for Kubernetes
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/aws/eks-charts
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/eks-charts
maintainers:
  - name: Mitchell Murphy