# namespace to deploy Chart to
namespace: kube-system

# nameOverride: Used to override name of chart
nameOverride: ""
# fullnameOverride: Used to override the full name of the application
fullnameOverride: ""

# replicaCount: Number of replicas
replicaCount: 1

image:
  # registry
  registry: 123456789.dkr.ecr.us-gov-east-1.amazonaws.com
  # image.repository: Repository of image to pull for deployment
  repository: security/admission/dp-image-admission-controller
  # image.tag: Tag of image to pull from repository. Default to appVersion
  tag: ""
  # image.pullPolicy: Policy of how to pull image
  pullPolicy: IfNotPresent

env:
  # use TLS
  tls: true
  logLevel: "trace"
  # registry to whitelist
  registry: ""
  logJson: false

serviceAccount:
  # serviceAccount.create: Whether to create a service account or not
  create: true
  # serviceAccount.name: The name of the service account to create or use
  name: ""

rbac:
  # rbac.create: Whether to create rbac resources or not
  create: true

webhookService:
  # webhookService.port: Incoming port used by webhook service
  port: 443
  # webhookService.targetPort: Target port used by webhook service
  targetPort: 443