apiVersion: v1
kind: Service
metadata:
  name: "image-admission-controller-webhook-service"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "dp-image-admission-controller.fullname" . }}
{{ include "dp-image-admission-controller.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.webhookService.port }}
      targetPort: {{ .Values.webhookService.targetPort }}
  selector:
    app: {{ template "dp-image-admission-controller.fullname" . }}