{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dp-image-admission-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "dp-image-admission-controller.labels" . | indent 4 }}
{{- end -}}