{ $tls := fromYaml ( include "dp-image-admission-controller.gen-certs" . ) }}
---
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "dp-image-admission-controller.fullname" . }}-webhook-config
  labels:
    app: {{ template "dp-image-admission-controller.fullname" . }}
{{ include "dp-image-admission-controller.labels" . | indent 4 }}
webhooks:
  - name: {{ template "dp-image-admission-controller.fullname" . }}.k8s.aws
    clientConfig:
      service:
        name: {{ template "dp-image-admission-controller.fullname" . }}-webhook-service
        namespace: {{ .Values.namespace }}
        path: "/mutate"
      caBundle: {{ $tls.caCert }}
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    admissionReviewVersions:
    - v1beta1
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values:
        - kube-system
        - kube-public
        - kube-node-lease
        - istio-system
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dp-image-admission-controller.fullname" . }}-webhook-certs
  namespace: {{ .Values.namespace }}
  labels:
{{ include "dp-image-admission-controller.labels" . | indent 4 }}
type: Opaque
data:
  cert.pem: {{ $tls.clientCert }}
  key.pem: {{ $tls.clientKey }}